name: Latest Versions
on:
  push:
    branches:
      - main
  pull_request:
   branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/geocompx/docker:python
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          # Install dependencies with pip and ignoring pinned versions:
          pip install pur
          # Install dev version of osmnx:
          pip install --no-cache-dir --upgrade --pre osmnx
          # Update requirements.txt with pur:
          pur -r requirements.txt
          # Update all packages (could also try --force-reinstall):
          # See https://pip.pypa.io/en/stable/development/architecture/upgrade-options/
          pip install -U --upgrade-strategy eager -r requirements.txt
      - name: Render
        run: |
          # test code:
          quarto render
          ls docs